# Dependencies
markdown:               kramdown
kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6

# Permalinks
permalink:              /:title/

# Setup
title:                  Peter Krautzberger
tagline:                'on the web'
description:            'Peter Krautzberger on the web'
url:                    https://www.peterkrautzberger.org

# sass
sass:
    sass_dir: public/css
    style: compressed

author:
  name:                 'Peter Krautzberger'
  url:                  https://www.peterkrautzberger.org

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
