# Dependencies
markdown:               kramdown
kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
highlighter:            pygments

# Permalinks
permalink:              /:title/

# Setup
title:                  Peter Krautzberger
tagline:                'on the web'
description:            'Peter Krautzberger on the web'
url:                    http://www.peterkrautzberger.org

author:
  name:                 'Peter Krautzberger'
  url:                  http://www.peterkrautzberger.org

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
