# Dependencies
markdown:               kramdown
kramdown: 
  input:                GFM
pygments:               true

# Permalinks
permalink:              pretty

# Setup
title:                  Peter Krautzberger
tagline:                'on the web'
description:            'Peter Krautzberger on the web'
url:                    http://www.peterkrautzberger.org
paginate:               1

author:
  name:                 'Peter Krautzberger'
  url:                  http://www.peterkrautzberger.org