# Dependencies
markdown:               kramdown
kramdown:
  input:                GFM
pygments:               true

# Permalinks
permalink:              /:title/

# Setup
title:                  Peter Krautzberger
tagline:                'on the web'
description:            'Peter Krautzberger on the web'
url:                    http://www.peterkrautzberger.org

author:
  name:                 'Peter Krautzberger'
  url:                  http://www.peterkrautzberger.org

gems:
  - jekyll-redirect-from
